# Generated by Django 4.2.2 on 2023-06-09 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='employ_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='employ_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('1', 'Головний інженер'), ('2', 'Інженер'), ('3', 'Майстер'), ('4', 'Робітник'), ('5', 'Стажер')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shift',
            name='producted',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
