# Generated by Django 4.2.2 on 2023-06-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coefs_start_shift_codes_shift_employ_end_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
