# Generated by Django 4.2.2 on 2023-06-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='employ_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='employ_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='producted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
