# Generated by Django 4.2.2 on 2023-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_employee_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to='avatars/'),
        ),
    ]
