# Generated by Django 4.2.2 on 2023-06-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to='avatars/<django.db.models.fields.CharField>'),
        ),
    ]
