# Generated by Django 4.2.2 on 2023-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_employer_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_shift_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('valid', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
